version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.4.9'
    ports:
      - '2181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:6.1.1'
    ports:
      - '9091:9091'
    environment:
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS: "INTERNAL://kafka:9090,EXTERNAL://:9091"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9090,EXTERNAL://localhost:9091"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka2:
    image: 'confluentinc/cp-kafka:6.1.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS: "INTERNAL://kafka2:9090,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:9090,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka3:
    image: 'confluentinc/cp-kafka:6.1.1'
    ports:
      - '9093:9093'
    environment:
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LISTENERS: "INTERNAL://kafka3:9090,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:9090,EXTERNAL://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper